export interface Book {
  id: number;
  zLibId: string | null;
  s3_storage_key: string;
  title: string;
  author: string | null;
  publisher: string | null;
  series: string | null;
  volume: string | null;
  series_index: number | null;
  edition: string | null;
  identifier: string | null;
  pages: number | null;
  description: string | null;
  google_books_id: string | null;
  open_library_key: string | null;
  hardcover_id?: string | null;
  amazon_asin: string | null;
  external_rating: number | null;
  external_rating_count: number | null;
  cover: string | null;
  extension: string | null;
  filesize: number | null;
  language: string | null;
  year: number | null;
  month: number | null;
  day: number | null;
  progress_storage_key: string | null;
  progress_updated_at: string | null;
  progress_percent: number | null;
  progress_before_read: number | null;
  rating: number | null;
  read_at: string | null;
  archived_at: string | null;
  exclude_from_new_books: boolean;
  createdAt: string | null;
  deleted_at: string | null;
  trash_expires_at: string | null;
  isDownloaded?: boolean;
}
